# https://docs.docker.com/compose/compose-file/compose-file-v3/
---
version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile-basic
    tty: true
    stdin_open: true
    volumes:
    - type: bind
      source: ../..
      target: /workspace
    ports:
    - target: 1313
      published: 1313
      mode: host
      protocol: tcp
