FROM mcr.microsoft.com/devcontainers/base:debian

EXPOSE 1313

ENV HUGO_VERSION='0.122.0' \
    TEMPDIR='/tmp'

USER root

# Install OS packages
RUN set -ex \
  && apt-get update \
  && apt-get -qqy install wget git vim.tiny \
  && apt-get clean

# Install Application: Hugo
RUN set -ex \
  && wget -O ${TEMPDIR}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
  && dpkg -i ${TEMPDIR}/hugo.deb \
  && rm -rf ${TEMPDIR}/hugo.deb

# sudo-enabled user from base-image
USER vscode

WORKDIR /workspace
ENTRYPOINT ["/bin/env", "zsh"]